version: '3.8'

services:
  web:
    build: .
    ports:
      - "5123:5123"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - DATABASE_URL=sqlite:///instance/gelato.db
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge 