version: '3.8'

services:
  web:
    build: .
    ports:
      - "5123:5123"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - DATABASE_URL=sqlite:////app/instance/gelato.db
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./instance:/app/instance:rw
      - ./migrations:/app/migrations:rw
    restart: unless-stopped
