"""Initial migration

Revision ID: c11dd7fc40cb
Revises: 
Create Date: 2025-04-13 11:26:08.377052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11dd7fc40cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('administration', sa.String(length=255), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('request_description', sa.Text(), nullable=False),
    sa.Column('preferred_response_format', sa.String(length=50), nullable=False),
    sa.Column('requester_name', sa.String(length=255), nullable=True),
    sa.Column('requester_email', sa.String(length=255), nullable=True),
    sa.Column('requester_address', sa.Text(), nullable=True),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('success_likelihood', sa.String(length=50), nullable=True),
    sa.Column('llm_suggestions', sa.Text(), nullable=True),
    sa.Column('reminder_requested', sa.Boolean(), nullable=True),
    sa.Column('reminder_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
